vps-debian:
  hosts:
    vps1-debian:
      ansible_host: vps1-debian
      ansible_user: root
      ansible_port: 22
      ansible_ssh_private_key_file: /keys/id_ed25519_root


vps-alpine:
  hosts:
    vps1:
      ansible_host: vps1
      ansible_user: root_user
      ansible_port: 2222
      ansible_ssh_private_key_file: /keys/id_ed25519_root
    vps2:
      ansible_host: vps2
      ansible_user: admin
      ansible_port: 2222
      ansible_ssh_private_key_file: /keys/id_ed25519_user
    vps3:
      ansible_host: vps3
      ansible_user: debian
      ansible_port: 2222
      ansible_password: password1234
  vars:
    ansible_python_interpreter: /usr/bin/python3

vps:
  children:
    vps-debian:
    vps-alpine:
