vps-debian:
  hosts:
    vps1-debian:
      ansible_host: vps1-debian
    vm-debian:
      ansible_host: 192.168.0.19
  

vps-alpine:
  hosts:
    vps1:
      ansible_host: vps1
    vps2:
      ansible_host: vps2
    vps3:
      ansible_host: vps3

all:
  children:
    vps-debian:
    vps-alpine:
