vps_debian:
  hosts:
    vps1_debian:
      ansible_host: vps1-debian
    # vm_debian:
    #   ansible_host: 192.168.0.19
    # vm_ubuntu:
    #   ansible_host: 192.168.0.15
  

vps_alpine:
  hosts:
    vps1:
      ansible_host: vps1
    vps2:
      ansible_host: vps2
    vps3:
      ansible_host: vps3

all:
  children:
    vps_debian:
    vps_alpine:
